### ISSUE TITLE
Persistent Error Running Shakemap - No module named 'esi_utils_gmice'

### ISSUE THREAD

**Issue by mrdimentio** [DOI-USGS/ghsc-esi-shakemap#11]
Hello GitHub community,

I hope this message finds you well. I'm reaching out regarding a persistent error I've been encountering while running Shakemap. Despite installing Shakemap on two different systems, the error continues to occur. Below is the relevant information:

`(shakemap) dimentio@dimentio:~$ shake ci3144585 model                                                                   INFO -- 2023-12-29 02:06:48 -- shake.main -- Running command model                                                      CRITICAL -- 2023-12-29 02:06:48 -- shake.main --                                                                        Earthquake: M6.6 Northridge, California                                                                                 Host: dimentio                                                                                                          Event ID: ci3144585                                                                                                     Exception: No module named 'esi_utils_gmice'                                                                            Stack Trace:   File "/home/dimentio/ghsc-esi-shakemap/src/shakemap/bin/shake.py", line 361, in main                         obj.execute()                                                                                                         File "/home/dimentio/miniconda/envs/shakemap/lib/python3.9/site-packages/shakemap_modules/coremods/model.py", line 263, in execute                                                                                                                self.gmice = get_object_from_config("gmice", "modeling", self.config)                                                 File "/home/dimentio/miniconda/envs/shakemap/lib/python3.9/site-packages/shakemap_modules/utils/utils.py", line 145, in get_object_from_config                                                                                                    return getattr(import_module(mpath), cname)(*args)                                                                    File "/home/dimentio/miniconda/envs/shakemap/lib/python3.9/importlib/__init__.py", line 127, in import_module             return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                      File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                            File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                      File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                            File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                      File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked  `

It seems to be related to the absence of the 'esi_utils_gmice' module. I have followed the installation process diligently, yet the issue persists.

Any insights or guidance on resolving this matter would be highly appreciated. Thank you in advance for your assistance.

Best regards,
Dimentio

**Comment by 77solihat** [comment]
Dimentio,
I have the same problem have you solve it.
best,
ali

**Comment by markhamnr** [comment]
I worked around this by modifying shakemap_profiles/default/install/config/modules.conf.  Under [gmice_modules], I changed "esi_utils_gmice.gmice.wgrw12" to just "gmice.wgrw12", and similarly for the other two lines.

I'm guessing that maybe shakelib isn't packaged quite right, such that esi-utils-gmice doesn't actually provide a module named esi_utils_gmice.

**Comment by cbworden-usgs** [comment]
If you're getting this error, the solution is described [here](https://code.usgs.gov/ghsc/esi/shakemap/-/wikis/Upgrading%20to%20v4.2) in the section on modifying the modules.conf config file.

I've fixed the bug, so new installations as of today shouldn't have this problem, but if you are upgrading a system that has existing configs (i.e., profiles) you'll need to follow the upgrade instructions in the wiki linked above.
